#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
seed_d1.py - Cloudflare D1 推文数据导入与种子生成脚本

特性：
1. 默认由 scripts/seed_data.json 生成标准 SQL 文件 (scripts/seed.sql)
2. 支持一键通过 Wrangler 写入本地或远程 D1:
     python scripts/seed_d1.py --local
     python scripts/seed_d1.py --remote
3. 遵循 12-Factor 与 Agent Relay Hygiene 规范，零私有环境依赖，完全基于标准库。
"""

import os
import sys
import json
import argparse
import subprocess
from pathlib import Path


def escape_sql(val):
    if val is None:
        return "NULL"
    if isinstance(val, (int, float)):
        return str(val)
    s = str(val).replace("'", "''")
    return f"'{s}'"


def generate_seed_sql(json_path, output_sql_path):
    with open(json_path, "r", encoding="utf-8") as f:
        tweets = json.load(f)

    print(f"📦 读取到 {len(tweets)} 条推文数据，正在生成 D1 种子 SQL 脚本...")

    sql_statements = [
        "-- Auto-generated by scripts/seed_d1.py",
        "-- Cloudflare D1 Seed Batch",
        ""
    ]

    for item in tweets:
        t_id = escape_sql(item.get("id", ""))
        filename = escape_sql(item.get("filename", ""))
        cat = escape_sql(item.get("category", ""))
        subcat = escape_sql(item.get("sub_category", ""))
        title = escape_sql(item.get("title", ""))
        author = escape_sql(item.get("author", ""))
        uname = escape_sql(item.get("username", ""))
        url = escape_sql(item.get("url", ""))
        created_at = escape_sql(item.get("created_at", ""))
        likes = int(item.get("likes", 0) or 0)
        retweets = int(item.get("retweets", 0) or 0)
        views = int(item.get("views", 0) or 0)
        has_media = 1 if item.get("has_media") else 0
        media_type = escape_sql(item.get("media_type", ""))
        images = escape_sql(json.dumps(item.get("images", []), ensure_ascii=False))
        videos = escape_sql(json.dumps(item.get("videos", []), ensure_ascii=False))
        snippet = escape_sql(item.get("snippet", ""))
        body_raw = escape_sql(item.get("body_raw", ""))
        body_html = escape_sql(item.get("body_html", ""))
        avatar = escape_sql(item.get("avatar", ""))

        sql = (
            f"INSERT OR REPLACE INTO tweets ("
            f"id, filename, category, sub_category, title, author, username, url, created_at, "
            f"likes, retweets, views, has_media, media_type, images, videos, snippet, body_raw, body_html, avatar"
            f") VALUES ("
            f"{t_id}, {filename}, {cat}, {subcat}, {title}, {author}, {uname}, {url}, {created_at}, "
            f"{likes}, {retweets}, {views}, {has_media}, {media_type}, {images}, {videos}, {snippet}, {body_raw}, {body_html}, {avatar}"
            f");"
        )
        sql_statements.append(sql)

    output_sql_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_sql_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_statements) + "\n")

    print(f"✅ 成功生成 SQL 文件: {output_sql_path} (包含 {len(tweets)} 条 INSERT 语句)")
    return len(tweets)


def main():
    parser = argparse.ArgumentParser(description="Cloudflare D1 种子数据管理工具")
    parser.add_argument("--db-name", default="x-bookmarks", help="D1 数据库绑定名称 (默认: x-bookmarks)")
    parser.add_argument("--local", action="store_true", help="调用 wrangler 执行本地 D1 数据库写入")
    parser.add_argument("--remote", action="store_true", help="调用 wrangler 执行远程生产 D1 数据库写入")
    parser.add_argument("--sql-only", action="store_true", help="仅生成 SQL 文件，不调用 wrangler 执行")
    args = parser.parse_args()

    root_dir = Path(__file__).resolve().parent.parent
    json_path = root_dir / "scripts" / "seed_data.json"
    sql_path = root_dir / "scripts" / "seed.sql"

    if not json_path.exists():
        print(f"❌ 找不到数据文件: {json_path}")
        sys.exit(1)

    # 1. 生成 SQL 种子
    generate_seed_sql(json_path, sql_path)

    # 2. 如果指定了 --local 或 --remote，调用 wrangler d1 execute
    if args.local or args.remote:
        target_flag = "--local" if args.local else "--remote"
        cmd = ["npx", "wrangler", "d1", "execute", args.db_name, target_flag, f"--file={sql_path}"]
        print(f"\n🚀 正在执行命令: {' '.join(cmd)}")
        try:
            res = subprocess.run(cmd, cwd=root_dir, check=True, shell=True)
            print(f"\n🎉 D1 数据成功写入 ({target_flag})！")
        except subprocess.CalledProcessError as e:
            print(f"\n❌ 执行失败 (退出码 {e.returncode})，请确保已安装 wrangler 并正确配置 D1 绑定。")
            sys.exit(e.returncode)
    else:
        print("\n💡 提示：")
        print(f"  - 导入本地开发库: python scripts/seed_d1.py --local")
        print(f"  - 导入远程生产库: python scripts/seed_d1.py --remote")
        print(f"  - 或直接使用 wrangler 命令: npx wrangler d1 execute {args.db_name} --local --file=scripts/seed.sql")


if __name__ == "__main__":
    main()
