#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
sync_config.py - 单一真源配置与提示词编译投影器 (Agent Relay Hygiene v1.1)

职责：
1. 以根目录 config.toml 为绝对单一真源，消除任何代码层面的配置硬编码；
2. 以 prompts/classify_system.txt 为提示词解耦资产的绝对单一真源；
3. 将上述资产安全投影编译至 src/_config_data.py，专供无本地磁盘的 Cloudflare Worker 边缘环境导入；
4. 保证本地开发与云端边缘生产永远使用完全相同的配置，杜绝配置漂移。
"""

import sys
import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
CONFIG_TOML_PATH = BASE_DIR / "config.toml"
PROMPT_CLASSIFY_PATH = BASE_DIR / "prompts" / "classify_system.txt"
TARGET_OUTPUT_PATH = BASE_DIR / "src" / "_config_data.py"


def generate_content() -> str:
    if not CONFIG_TOML_PATH.exists():
        print(f"❌ 错误: 未找到单一真源配置文件 {CONFIG_TOML_PATH}")
        sys.exit(1)

    with open(CONFIG_TOML_PATH, "r", encoding="utf-8") as f:
        config_toml_str = f.read()

    prompt_classify_str = ""
    if PROMPT_CLASSIFY_PATH.exists():
        with open(PROMPT_CLASSIFY_PATH, "r", encoding="utf-8") as f:
            prompt_classify_str = f.read()

    generated_code = f'''# -*- coding: utf-8 -*-
"""
==============================================================================
⚠️ 自动生成文件 (AUTO-GENERATED BY scripts/sync_config.py)
------------------------------------------------------------------------------
严禁手动编辑此文件！本文件是根目录配置与提示词资产在 Worker 边缘运行时的镜像投影。
唯一真源 (Single Source of Truth)：
  - config.toml (工程与业务解耦参数)
  - prompts/classify_system.txt (外部提示词资产)
==============================================================================
"""

CONFIG_TOML_CONTENT = {json.dumps(config_toml_str, ensure_ascii=False)}

PROMPT_CLASSIFY_CONTENT = {json.dumps(prompt_classify_str, ensure_ascii=False)}
'''
    return generated_code


def sync_config(check_only: bool = False) -> bool:
    new_content = generate_content()

    existing_content = ""
    if TARGET_OUTPUT_PATH.exists():
        with open(TARGET_OUTPUT_PATH, "r", encoding="utf-8") as f:
            existing_content = f.read()

    is_identical = (new_content == existing_content)

    if check_only:
        if is_identical:
            print("  ✓ 单一真源镜像同步有效: config.toml -> src/_config_data.py (100% 对齐)")
            return True
        else:
            print("  ❌ 单一真源镜像不同步: src/_config_data.py 与 config.toml 不一致")
            return False

    if not is_identical:
        with open(TARGET_OUTPUT_PATH, "w", encoding="utf-8") as f:
            f.write(new_content)
        print("⚡ 成功将 config.toml 与 prompts 同步至 src/_config_data.py")
    else:
        print("✓ src/_config_data.py 已是最新，无需更新")
    return True


if __name__ == "__main__":
    check_mode = "--check" in sys.argv
    success = sync_config(check_only=check_mode)
    if not success and check_mode:
        sys.exit(1)
